#!/bin/sh
cd "${0%/*}" || exit                                # Run from this directory
. ${WM_PROJECT_DIR:?}/bin/tools/RunFunctions        # Tutorial run functions
#------------------------------------------------------------------------------

rm -r processor*

runApplication decomposePar
runApplication mpirun -np 4 --oversubscribe pimpleFoam -parallel
runApplication reconstructPar -constan

#------------------------------------------------------------------------------
