#!/bin/sh
cd "${0%/*}" || exit                                # Run from this directory
. ${WM_PROJECT_DIR:?}/bin/tools/CleanFunctions      # Tutorial clean functions
#------------------------------------------------------------------------------

rm -rf [1-9]*           # rimuove le cartelle dei timestep (tranne la 0)
rm -rf processor*       # rimuove le cartelle dei processori

#------------------------------------------------------------------------------
