#!/bin/sh
cd "${0%/*}" || exit                                # Run from this directory
. ${WM_PROJECT_DIR:?}/bin/tools/RunFunctions        # Tutorial run functions
#------------------------------------------------------------------------------

runApplication blockMesh
runApplication surfaceFeatureExtract
runApplication snappyHexMesh -overwrite
# runApplication decomposePar
# runApplication mpirun -np 4 --oversubscribe snappyHexMesh -overwrite -parallel
# runApplication reconstructParMesh -constant
runApplication checkMesh

#------------------------------------------------------------------------------
